---
# File: docker-compose.yml

version: "3.7"

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      TZ: Europe/Amsterdam

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

  redis:
    restart: always
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo-server
    ports:
      - 27017:27017
