openapi: 3.0.3
info:
  title: Simple Authentication API
  version: 0.0.1
servers:
  - url: http://localhost:3000
tags:
  - name: auth
    description: Operations about authentication
paths:
  /auth:
    post:
      tags:
        - auth
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: username
                password:
                  type: string
                  example: password
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        '400':
          description: Bad request
        '401':
          description: Unauthorized
