openapi: 3.0.3
info:
  title: Simple Authentication API
  version: 0.0.1
servers:
  - url: http://localhost:3000

tags:
  - name: auth
    description: Operations about authentication

paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Authenticate user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: username
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - token
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Missing username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
        errors:
          type: object

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
