---
openapi: 3.0.3

info:
  title: Simple Authentication API
  version: 0.0.1
  description: This is a sample server for a pet store.
  termsOfService: https://www.groveld.com/terms
  contact:
    name: API Support
    email: support@groveld.com
    url: https://www.groveld.com/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
  - url: https://api.groveld.com/v1

tags:
  - name: auth
    description: Everything about authentication
  - name: users
    description: Everything about users
  - name: certificates
    description: Everything about certificates
  - name: root
    description: Everything about root functions

paths:
  /ping:
    get:
      tags:
        - root
      summary: 'Get Server Information'
      operationId: ping
      security: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
  /data:
    get:
      tags:
        - root
      summary: Get data
      operationId: getData
      responses:
        '200':
          description: Get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
        '404':
          description: 'no data found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      tags:
        - auth
      summary: Authenticate user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: username
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - access_token
                  - refresh_token
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: Missing username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      tags:
        - auth
      summary: request new refresh token
      operationId: requestRefreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - access_token
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Request refresh token successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - access_token
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
        '400':
          description: Missing access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid or expired access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/logout:
    post:
      tags:
        - auth
      summary: Logout user
      operationId: logoutUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - access_token
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Missing username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    post:
      tags:
        - users
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Create new user successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - user_id
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
        '400':
          description: Missing user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - users
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: Get all users successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - users
                properties:
                  message:
                    type: string
                  users:
                    type: object
        '400':
          description: Missing username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{id}:
    get:
      tags:
        - users
      summary: Authenticate user
      operationId: getUserId
      responses:
        '200':
          description: Get user id successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - user
                properties:
                  message:
                    type: string
                  user:
                    type: object
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ServerInfo:
      type: 'object'
      required:
        - name
        - description
        - version
        - uptime
      properties:
        name:
          type: 'string'
        description:
          type: 'string'
        version:
          type: 'string'
        uptime:
          type: 'number'
    Error:
      type: object
      # required:
      #   - message
      #   - errors
      properties:
        message:
          type: string
        errors:
          type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
